import SEO from '../components/SEO';
import { AlertTriangle } from 'lucide-react';

export default function Disclaimer() {
  return (
    <div className="max-w-4xl mx-auto space-y-8 text-left py-6">
      <SEO
        title="Disclaimer | Toolique"
        description="Read the disclaimer for Toolique. All calculations are for estimation and educational purposes only and should not be treated as financial advice."
      />

      <div className="space-y-4">
        <h1 className="text-3xl md:text-5xl font-black text-slate-900 dark:text-white flex items-center gap-2.5">
          <AlertTriangle className="w-10 h-10 text-teal-600 dark:text-teal-400 shrink-0" />
          Disclaimer
        </h1>
        <p className="text-xs text-slate-400 font-semibold uppercase tracking-wider">Last Updated: June 16, 2026</p>
      </div>

      <div className="p-8 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800/80 shadow-sm space-y-6 text-sm text-slate-655 dark:text-slate-400 leading-relaxed">
        <div className="p-4 rounded-xl bg-amber-500/5 border border-amber-500/10 flex items-start gap-2.5 text-xs text-amber-700 dark:text-amber-400 font-semibold">
          <AlertTriangle className="w-5 h-5 shrink-0 mt-0.5" />
          <div>
            IMPORTANT: The calculations generated by this website are estimates only and should not be used as official references for financial planning, corporate bookkeeping, or legal tax declarations.
          </div>
        </div>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-850 dark:text-white">1. Financial Estimations & Market Risks</h2>
          <p>
            The SIP Mutual Fund Calculator, EMI Loan Calculator, and other investment estimators on Toolique use mathematical formulas to project future values based on constant interest rates. 
            Mutual fund investments and interest rates are subject to market volatility. Actual maturity values, returns, or loan splits may vary significantly based on bank policies and market conditions.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-850 dark:text-white">2. Tax Calculations Disclaimer (GST, TDS, Salary)</h2>
          <p>
            Our tax calculators (GST Calculator, TDS Calculator, In-hand Salary Calculator) are updated to represent standard Indian tax codes. However, tax compliance rules, exemptions, state-level surcharges, and municipal professional tax rates change frequently.
          </p>
          <p>
            The calculations provided by these tools do not constitute certified tax advice. Users are strongly advised to consult with a registered Chartered Accountant (CA) or financial advisor before completing tax returns or drafting commercial contracts.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-850 dark:text-white">3. Code Formatting & Output Accuracy</h2>
          <p>
            Our developer tools (SQL Formatter, JSON Formatter & Validator) process scripts inside the browser context. While these utilities validate standard grammar, we cannot guarantee that structured edits will execute error-free in production databases or servers. Please back up critical scripts before running formatters.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-850 dark:text-white">4. No Professional-Client Relationship</h2>
          <p>
            Your usage of Toolique does not establish a professional advisor-client relationship between you and the owners or administrators of this website.
          </p>
        </section>
      </div>
    </div>
  );
}

