import SEO from '../components/SEO';
import { FileText } from 'lucide-react';

export default function TermsConditions() {
  return (
    <div className="max-w-4xl mx-auto space-y-8 text-left py-6">
      <SEO
        title="Terms & Conditions | Toolique"
        description="Review the terms and conditions for using Toolique calculators, formatters, and browser-based utility tools."
      />

      <div className="space-y-4">
        <h1 className="text-3xl md:text-5xl font-black text-slate-900 dark:text-white flex items-center gap-2.5">
          <FileText className="w-10 h-10 text-teal-600 dark:text-teal-400 shrink-0" />
          Terms & Conditions
        </h1>
        <p className="text-xs text-slate-400 font-semibold uppercase tracking-wider">Last Updated: June 16, 2026</p>
      </div>

      <div className="p-8 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800/80 shadow-sm space-y-6 text-sm text-slate-655 dark:text-slate-400 leading-relaxed">
        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-850 dark:text-white">1. Acceptance of Terms</h2>
          <p>
            By accessing and using Toolique (referred to as "the website" or "our services"), you agree to comply with and be bound by these Terms & Conditions. If you do not agree, please discontinue using our site.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-850 dark:text-white">2. Permitted Use</h2>
          <p>
            Our calculators, converters, image optimizers, and developer utilities are provided for both personal and commercial use at zero cost. You are permitted to use the outputs generated by these tools (e.g. compressed images, formatted code, QR codes, financial reports) for business invoices, projects, or applications.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-850 dark:text-white">3. Intellectual Property</h2>
          <p>
            All custom components, designs, routing code, layout styles, and assets on Toolique are the property of the site owner and protected by applicable copyright and trademark laws. You may not republish, scrape, or hotlink the codebase or layout without explicit permission.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-850 dark:text-white">4. No Warranties</h2>
          <p>
            The tools and services on this website are provided on an <strong>"as-is" and "as-available"</strong> basis. While we strive to ensure high mathematical accuracy for financial calculations (GST, EMI, SIP, TDS) and code formatting outputs, Toolique makes no warranties, expressed or implied, regarding errors, downtime, or mathematical anomalies.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-850 dark:text-white">5. Limitation of Liability</h2>
          <p>
            In no event shall Toolique or its creators be held liable for any damages (including, without limitation, financial loss, tax penalties, data loss, or business interruption) arising from the use or inability to use the outputs of our calculators.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-850 dark:text-white">6. Governing Law</h2>
          <p>
            Any claims relating to Toolique shall be governed by the laws of India, without regard to its conflict of law provisions.
          </p>
        </section>
      </div>
    </div>
  );
}

