import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  ShieldCheck, 
  Scale, 
  CheckCircle2, 
  Lock, 
  HelpCircle, 
  ChevronDown, 
  Globe2, 
  ServerOff, 
  Code2, 
  Sparkles, 
  AlertCircle,
  Building,
  UserCheck
} from 'lucide-react';
import { Link } from 'react-router-dom';
import SEO from '../components/SEO';

interface TermSection {
  id: string;
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  badge?: string;
  content: React.ReactNode;
}

const TERMS_FAQS = [
  {
    q: 'Can I use Toolique calculations and generated assets for commercial client projects?',
    a: 'Yes, absolutely. All outputs generated by Toolique—including PDF invoices, formatted code snippets, 3D lithophane STL files, BOQ cost estimations, and architectural graphs—are 100% royalty-free and can be used in commercial client deliverables, tax filings, and production software.'
  },
  {
    q: 'Who owns the data I input and the files I generate on Toolique?',
    a: 'You retain 100% exclusive ownership of all inputs, scripts, tokens, and files processed on Toolique. Because our platform executes strictly client-side inside your browser RAM, Toolique never stores, claims rights to, or monetizes any user content.'
  },
  {
    q: 'Are Toolique tools guaranteed to be 100% mathematically accurate for tax filing?',
    a: 'While our calculation algorithms are rigorously verified against statutory formulas (such as the Income Tax Act 1961, Union Budget 2025-26, and National Building Code 2016), outputs are provided as estimation aids and should be cross-verified with a licensed Chartered Accountant (CA) or certified engineer.'
  },
  {
    q: 'Is there any subscription fee, API rate limiting, or hidden usage charge?',
    a: 'No. Toolique is committed to radical open access. All 274+ calculators and utilities are free to use without mandatory user accounts, subscription tiers, or paywalled export features.'
  },
  {
    q: 'What law governs the terms of service for Toolique?',
    a: 'These terms are governed by and construed in accordance with the laws of India, including the Information Technology Act, 2000 and the Digital Personal Data Protection Act, 2023, under the jurisdiction of courts in Maharashtra, India.'
  }
];

export default function TermsConditions() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const toggleFaq = (idx: number) => {
    setOpenFaq(openFaq === idx ? null : idx);
  };

  const termsSchema = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'WebPage',
        '@id': 'https://www.toolique.in/terms#webpage',
        'url': 'https://www.toolique.in/terms',
        'name': 'Terms & Conditions | Toolique - Open-Access Utility Platform',
        'description': 'Official Terms and Conditions for Toolique. Review user rights, zero-knowledge data ownership, permitted commercial use, and statutory disclaimers.',
        'breadcrumb': {
          '@type': 'BreadcrumbList',
          'itemListElement': [
            {
              '@type': 'ListItem',
              'position': 1,
              'name': 'Home',
              'item': 'https://www.toolique.in/'
            },
            {
              '@type': 'ListItem',
              'position': 2,
              'name': 'Terms & Conditions',
              'item': 'https://www.toolique.in/terms'
            }
          ]
        }
      },
      {
        '@type': 'FAQPage',
        '@id': 'https://www.toolique.in/terms#faq',
        'mainEntity': TERMS_FAQS.map(faq => ({
          '@type': 'Question',
          'name': faq.q,
          'acceptedAnswer': {
            '@type': 'Answer',
            'text': faq.a
          }
        }))
      }
    ]
  };

  const termsSections: TermSection[] = [
    {
      id: 'acceptance',
      icon: UserCheck,
      title: '1. Acceptance of Terms & Digital Binding',
      badge: 'Legal Binding',
      content: (
        <div className="space-y-3">
          <p>
            By accessing, browsing, or utilizing the web applications, mathematical calculators, developer formatters, and engineering utilities available on <strong>Toolique</strong> (accessible via toolique.in), you acknowledge that you have read, understood, and agree to be bound by these Terms & Conditions and our <Link to="/privacy-policy" className="text-indigo-600 dark:text-indigo-400 font-bold hover:underline">Privacy Policy</Link>.
          </p>
          <p>
            These terms constitute a legally binding electronic agreement between you (the "User") and Toolique in accordance with the <em>Information Technology Act, 2000</em> and the <em>Digital Personal Data Protection Act, 2023</em>. If you do not agree with any part of these terms, you must immediately discontinue use of the platform.
          </p>
        </div>
      )
    },
    {
      id: 'permitted-use',
      icon: CheckCircle2,
      title: '2. Permitted Commercial & Personal Use',
      badge: 'Open Access',
      content: (
        <div className="space-y-3">
          <p>
            Toolique provides 274+ browser-based utilities free of charge for both individual and commercial endeavors. You are explicitly authorized to:
          </p>
          <ul className="space-y-2 list-disc pl-5">
            <li>
              <strong>Commercial Client Deliverables:</strong> Generate and export financial balance sheets, GST invoices, BOQ construction estimates, 3D printing slicing configs, and formatted code scripts for paying commercial clients.
            </li>
            <li>
              <strong>Academic & Engineering Research:</strong> Utilize our structural, economic, mathematical, and algorithmic tools for educational research, thesis calculations, and simulation benchmarks.
            </li>
            <li>
              <strong>Offline Workflow Integration:</strong> Install Toolique as a Progressive Web Application (PWA) on enterprise workstations, laptops, or air-gapped lab computers without licensing fees.
            </li>
          </ul>
        </div>
      )
    },
    {
      id: 'data-ownership',
      icon: ServerOff,
      title: '3. User Content & Zero-Knowledge Sovereignty',
      badge: 'Data Sovereignty',
      content: (
        <div className="space-y-3">
          <p>
            Toolique operates under a strict <strong>Zero-Knowledge Client-Side Architecture</strong>. When you input source code, SQL queries, JWT tokens, employee payroll numbers, or architectural dimensions:
          </p>
          <div className="p-4 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 text-xs sm:text-sm text-emerald-900 dark:text-emerald-300 font-semibold leading-relaxed flex items-start gap-3">
            <ShieldCheck className="w-5 h-5 text-emerald-500 shrink-0 mt-0.5" />
            <div>
              <strong>100% Exclusive Ownership:</strong> You retain complete intellectual property and proprietary ownership of all data you input and all files you generate. Toolique claims 0 copyright, licensing rights, or access to your generated outputs.
            </div>
          </div>
        </div>
      )
    },
    {
      id: 'intellectual-property',
      icon: Code2,
      title: '4. Platform Intellectual Property & Trademarks',
      badge: 'Copyright',
      content: (
        <div className="space-y-3">
          <p>
            All custom UI components, application logic, brand marks, logos, vector icons, domain names, and algorithmic compilation routines comprising the Toolique website are the exclusive intellectual property of Toolique and its creator.
          </p>
          <p>
            You may not scrape our application assets for mirror redistribution, repackage our closed-source frontend bundles into commercial clone sites, or systematically harvest our static assets without prior written consent.
          </p>
        </div>
      )
    },
    {
      id: 'disclaimer-warranties',
      icon: AlertCircle,
      title: '5. "As-Is" Provision & Accuracy Disclaimers',
      badge: 'Safe Harbor',
      content: (
        <div className="space-y-3">
          <p>
            All tools and calculators are provided on an <strong>"AS-IS" and "AS-AVAILABLE"</strong> basis without warranties of any kind, whether express, statutory, or implied.
          </p>
          <p>
            While our development team rigorously tests every mathematical model against statutory guidelines (such as IS 456:2000, NBC 2016, and Central Board of Direct Taxes rules), computational models are subject to rounding differences, floating-point precision factors, and statutory code revisions. You are advised to verify critical calculations independently.
          </p>
        </div>
      )
    },
    {
      id: 'limitation-liability',
      icon: Scale,
      title: '6. Limitation of Liability',
      badge: 'Legal Protection',
      content: (
        <div className="space-y-3">
          <p>
            To the maximum extent permitted by applicable law, in no event shall Toolique, its founder, contributors, or service providers be liable for any direct, indirect, punitive, incidental, special, consequential, or exemplary damages—including but not limited to financial losses, tax penalties, construction structural defects, data corruption, or business interruption—arising out of or in connection with the use or inability to use our tools.
          </p>
        </div>
      )
    },
    {
      id: 'acceptable-use',
      icon: Lock,
      title: '7. Prohibited Misuse & Security Integrity',
      content: (
        <div className="space-y-3">
          <p>
            When utilizing Toolique, you agree not to:
          </p>
          <ul className="space-y-1.5 list-disc pl-5 text-xs sm:text-sm">
            <li>Engage in automated denial-of-service (DDoS) attacks against our CDN edge nodes.</li>
            <li>Attempt to bypass client-side security sandboxes or inject malicious scripts into our web worker channels.</li>
            <li>Use the platform for any unlawful purpose under the laws of India or your local jurisdiction.</li>
          </ul>
        </div>
      )
    },
    {
      id: 'governing-law',
      icon: Building,
      title: '8. Governing Law & Dispute Resolution',
      content: (
        <div className="space-y-3">
          <p>
            These Terms & Conditions are governed by and construed in accordance with the substantive laws of the Republic of India. Any disputes, claims, or controversies arising out of or relating to these terms shall be submitted to the exclusive jurisdiction of the competent courts located in Maharashtra, India.
          </p>
        </div>
      )
    },
    {
      id: 'modifications',
      icon: Globe2,
      title: '9. Revisions & Statutory Updates',
      content: (
        <div className="space-y-3">
          <p>
            We reserve the right to modify these Terms & Conditions at any time to reflect platform improvements, new tool additions, or statutory regulatory mandates. Continued use of Toolique following the posting of revised terms indicates your acceptance of those modifications.
          </p>
          <p>
            If you have any questions regarding these terms, please contact our legal and engineering team via our{' '}
            <Link to="/contact" className="text-indigo-600 dark:text-indigo-400 font-bold hover:underline">
              Contact Page
            </Link>.
          </p>
        </div>
      )
    }
  ];

  return (
    <div className="max-w-6xl mx-auto space-y-16 text-left py-8 px-4 sm:px-6 animate-fadeIn">
      <SEO
        title="Terms & Conditions | Toolique - User Rights & Open Access"
        description="Official Terms and Conditions for Toolique. Review zero-knowledge data ownership, permitted commercial usage rights, and statutory compliance standards."
        keywords={[
          'toolique terms and conditions',
          'toolique terms of service',
          'client side tools license',
          'commercial use free calculators',
          'dpdp act compliance terms'
        ]}
        schemaMarkup={termsSchema}
      />

      {/* --- 1. HERO SECTION WITH AMBIENT PASTEL GLOW --- */}
      <div className="relative text-center max-w-4xl mx-auto space-y-6 pt-4">
        {/* Ambient Glows */}
        <div 
          className="absolute -left-20 top-1/2 -translate-y-1/2 w-72 h-72 rounded-full pointer-events-none opacity-0 dark:opacity-100 blur-3xl transition-opacity duration-500 -z-10"
          style={{ background: 'radial-gradient(circle, rgba(56, 189, 248, 0.22) 0%, transparent 70%)' }}
          aria-hidden="true"
        />
        <div 
          className="absolute -right-20 top-1/2 -translate-y-1/2 w-72 h-72 rounded-full pointer-events-none opacity-0 dark:opacity-100 blur-3xl transition-opacity duration-500 -z-10"
          style={{ background: 'radial-gradient(circle, rgba(168, 85, 247, 0.22) 0%, transparent 70%)' }}
          aria-hidden="true"
        />

        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full text-xs font-black uppercase tracking-wider bg-white/80 dark:bg-zinc-900/80 text-indigo-700 dark:text-indigo-400 border border-pastel-indigo/60 dark:border-indigo-800/60 shadow-xs backdrop-blur-sm"
        >
          <Scale className="w-4 h-4 text-indigo-500" />
          <span>Statutory Terms of Service • Commercial Freedom • Zero Data Lock-In</span>
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="text-3xl sm:text-5xl md:text-6xl font-black text-zinc-900 dark:text-white tracking-tight leading-[1.12]"
        >
          Terms of Service &{' '}
          <span className="bg-clip-text text-transparent bg-gradient-to-r from-teal-600 via-indigo-600 to-purple-600 dark:from-teal-400 dark:via-indigo-400 dark:to-purple-400">
            User Rights
          </span>
        </motion.h1>

        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.2 }}
          className="text-base sm:text-lg text-zinc-650 dark:text-zinc-300 leading-relaxed max-w-3xl mx-auto font-medium"
        >
          Transparent, developer-first terms designed for radical open access. Learn about your unrestricted commercial usage rights, full data sovereignty, and our zero-knowledge execution guarantee.
        </motion.p>

        <div className="flex items-center justify-center gap-3 pt-2 text-xs font-bold text-zinc-400 uppercase tracking-wider">
          <span>Effective Date: September 2026</span>
          <span>•</span>
          <span>Version 2.4</span>
        </div>
      </div>

      {/* --- 2. THE 4 PILLARS OF OUR TERMS --- */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="saas-card p-5 rounded-2xl border border-zinc-200/80 dark:border-zinc-800/80 space-y-2 bg-white/80 dark:bg-zinc-900/80 backdrop-blur-md shadow-2xs">
          <div className="p-2.5 rounded-xl bg-teal-500/10 text-teal-600 dark:text-teal-400 w-fit">
            <Sparkles className="w-5 h-5" />
          </div>
          <div className="text-sm font-black text-zinc-900 dark:text-white">Commercial Freedom</div>
          <div className="text-xs text-zinc-500 dark:text-zinc-400 leading-relaxed font-medium">
            Use all calculations, outputs, and generated files in commercial projects for free.
          </div>
        </div>

        <div className="saas-card p-5 rounded-2xl border border-zinc-200/80 dark:border-zinc-800/80 space-y-2 bg-white/80 dark:bg-zinc-900/80 backdrop-blur-md shadow-2xs">
          <div className="p-2.5 rounded-xl bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 w-fit">
            <ServerOff className="w-5 h-5" />
          </div>
          <div className="text-sm font-black text-zinc-900 dark:text-white">100% User Ownership</div>
          <div className="text-xs text-zinc-500 dark:text-zinc-400 leading-relaxed font-medium">
            You own all inputs and outputs. We never store, claim, or monetize your data.
          </div>
        </div>

        <div className="saas-card p-5 rounded-2xl border border-zinc-200/80 dark:border-zinc-800/80 space-y-2 bg-white/80 dark:bg-zinc-900/80 backdrop-blur-md shadow-2xs">
          <div className="p-2.5 rounded-xl bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 w-fit">
            <Lock className="w-5 h-5" />
          </div>
          <div className="text-sm font-black text-zinc-900 dark:text-white">Zero Paywalls</div>
          <div className="text-xs text-zinc-500 dark:text-zinc-400 leading-relaxed font-medium">
            No forced sign-ups, no monthly tiers, and no locked features across 274+ tools.
          </div>
        </div>

        <div className="saas-card p-5 rounded-2xl border border-zinc-200/80 dark:border-zinc-800/80 space-y-2 bg-white/80 dark:bg-zinc-900/80 backdrop-blur-md shadow-2xs">
          <div className="p-2.5 rounded-xl bg-purple-500/10 text-purple-600 dark:text-purple-400 w-fit">
            <Scale className="w-5 h-5" />
          </div>
          <div className="text-sm font-black text-zinc-900 dark:text-white">Statutory Alignment</div>
          <div className="text-xs text-zinc-500 dark:text-zinc-400 leading-relaxed font-medium">
            Full alignment with Indian IT Act 2000 and DPDP Act 2023 regulations.
          </div>
        </div>
      </div>

      {/* --- 3. DETAILED TERMS SECTIONS --- */}
      <div className="space-y-6">
        {termsSections.map((sec) => {
          const Icon = sec.icon;
          return (
            <div
              key={sec.id}
              id={sec.id}
              className="saas-card p-6 sm:p-8 rounded-3xl border border-zinc-200/80 dark:border-zinc-800/80 space-y-4 shadow-sm"
            >
              <div className="flex items-center justify-between flex-wrap gap-2 pb-2 border-b border-zinc-100 dark:border-zinc-800/80">
                <div className="flex items-center gap-3">
                  <div className="p-2.5 rounded-2xl bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border border-indigo-500/20">
                    <Icon className="w-5 h-5" />
                  </div>
                  <h2 className="text-lg sm:text-xl font-black text-zinc-900 dark:text-white">
                    {sec.title}
                  </h2>
                </div>
                {sec.badge && (
                  <span className="px-2.5 py-0.5 rounded-full bg-indigo-500/10 text-indigo-700 dark:text-indigo-300 text-[10px] font-black uppercase tracking-wider border border-indigo-500/20">
                    {sec.badge}
                  </span>
                )}
              </div>

              <div className="text-xs sm:text-sm text-zinc-650 dark:text-zinc-300 leading-relaxed font-medium">
                {sec.content}
              </div>
            </div>
          );
        })}
      </div>

      {/* --- 4. TERMS & USAGE FAQS --- */}
      <div className="saas-card p-6 sm:p-8 rounded-3xl border border-zinc-200/80 dark:border-zinc-800/80 space-y-6">
        <div>
          <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase bg-indigo-500/10 text-indigo-700 dark:text-indigo-400 border border-indigo-500/20 mb-1.5">
            <HelpCircle className="w-3 h-3 text-indigo-500" />
            <span>Usage & Legal FAQs</span>
          </div>
          <h2 className="text-xl sm:text-2xl font-black text-zinc-900 dark:text-white">
            Frequently Asked Terms & Licensing Questions
          </h2>
        </div>

        <div className="divide-y divide-zinc-200/60 dark:divide-zinc-800/60">
          {TERMS_FAQS.map((faq, idx) => (
            <div key={idx} className="py-4">
              <button
                onClick={() => toggleFaq(idx)}
                className="w-full flex justify-between items-center text-left text-sm font-black text-zinc-900 dark:text-white cursor-pointer group"
              >
                <span className="group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors">
                  {faq.q}
                </span>
                <ChevronDown
                  className={`w-4 h-4 text-zinc-400 transition-transform duration-200 shrink-0 ml-2 ${
                    openFaq === idx ? 'rotate-180 text-indigo-600' : ''
                  }`}
                />
              </button>

              <AnimatePresence>
                {openFaq === idx && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    exit={{ opacity: 0, height: 0 }}
                    transition={{ duration: 0.2 }}
                    className="overflow-hidden"
                  >
                    <p className="text-xs text-zinc-650 dark:text-zinc-400 leading-relaxed font-medium pt-3 pr-4">
                      {faq.a}
                    </p>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ))}
        </div>
      </div>

      {/* --- 5. CALL TO ACTION & CROSS-LINKS --- */}
      <div className="saas-card p-8 sm:p-10 rounded-3xl border border-indigo-500/30 bg-gradient-to-br from-teal-500/5 via-indigo-500/5 to-purple-500/5 space-y-6 text-center shadow-md">
        <div className="max-w-2xl mx-auto space-y-2">
          <h3 className="text-2xl sm:text-3xl font-black text-zinc-900 dark:text-white">
            Built for Developers, Engineers & Creators
          </h3>
          <p className="text-xs sm:text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed">
            Unrestricted access to 274+ tools with complete privacy and zero commercial royalties.
          </p>
        </div>

        <div className="flex flex-wrap items-center justify-center gap-3 pt-2">
          <Link
            to="/tools"
            className="saas-button-primary py-3 px-6 text-xs font-extrabold inline-flex items-center gap-2 shadow-md cursor-pointer"
          >
            <Sparkles className="w-4 h-4" />
            <span>Explore All 274+ Tools</span>
          </Link>

          <Link
            to="/privacy-policy"
            className="saas-button-secondary py-3 px-6 text-xs font-extrabold inline-flex items-center gap-2 cursor-pointer"
          >
            <ShieldCheck className="w-4 h-4" />
            <span>Privacy Policy</span>
          </Link>

          <Link
            to="/disclaimer"
            className="saas-button-secondary py-3 px-6 text-xs font-extrabold inline-flex items-center gap-2 cursor-pointer"
          >
            <AlertCircle className="w-4 h-4" />
            <span>Calculation Disclaimers</span>
          </Link>
        </div>
      </div>
    </div>
  );
}

